# This file was generated by GoReleaser. DO NOT EDIT.
cask "actl" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "7053bae5a3294d63d6c015f7532e219c602e9da12eb3532bc696c83f1b9c8583"
      url "https://github.com/ruzmuh/actl/releases/download/v#{version}/actl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ffa75a1ec689f01e72946d7660781173c66c19c21c69a3da078d22e675bdd329"
      url "https://github.com/ruzmuh/actl/releases/download/v#{version}/actl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1953396fbe2cf16c17f4bcfc7a189f03e675db0ad1c297d002c90c18cf9eb955"
      url "https://github.com/ruzmuh/actl/releases/download/v#{version}/actl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "877984b572fd38e51b4f89d9fd46957b752be638108b2d85e16f201904a28f8e"
      url "https://github.com/ruzmuh/actl/releases/download/v#{version}/actl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "actl"
  desc "TUI-first interactive step-debugger for GitHub Actions workflows, running locally on act"
  homepage "https://github.com/ruzmuh/actl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "actl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/actl"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    actl requires Docker to be installed and running — it launches a real job container via act.
  EOS
end
