# This file was generated by GoReleaser. DO NOT EDIT.
cask "actl" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "d262d1626c66a4560ef70febf9b72bf94802c789faf445512e81abfb2bf21aae"
      url "https://github.com/ruzmuh/actl/releases/download/v#{version}/actl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "58f036dc5c5876faeb05b9d5e139689cf265dd5e81bd9e96b53fa73b8eb20c5c"
      url "https://github.com/ruzmuh/actl/releases/download/v#{version}/actl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b272374a3620d19a742124c0f71d4aa061be08e61a50b75c1f36468f26a348ee"
      url "https://github.com/ruzmuh/actl/releases/download/v#{version}/actl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "57107f4add71f560a0f566533cfc4bdb3ffdf4731e749fe2a24b2f82f68307f3"
      url "https://github.com/ruzmuh/actl/releases/download/v#{version}/actl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "actl"
  desc "TUI-first interactive step-debugger for GitHub Actions workflows, running locally on act"
  homepage "https://github.com/ruzmuh/actl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "actl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/actl"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    actl requires Docker to be installed and running — it launches a real job container via act.
  EOS
end
