# This file was generated by GoReleaser. DO NOT EDIT.
cask "actl" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "9ecd8ae895edc8f8bbd23fadd109920bc65450978ab2ec7dc3727df22cff2248"
      url "https://github.com/ruzmuh/actl/releases/download/v#{version}/actl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9ff37b59cb22cc89e1831bfb9dc2c6f7d38855f7e39f183c545f859bbea04b27"
      url "https://github.com/ruzmuh/actl/releases/download/v#{version}/actl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e134419a866c515032eda265fd3471a42b037d7d8ffae453f804628cabd6b17e"
      url "https://github.com/ruzmuh/actl/releases/download/v#{version}/actl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "50c342a1abc33762ccfb28fc418cd45084f3533158ddb64475c5cc4362a144b8"
      url "https://github.com/ruzmuh/actl/releases/download/v#{version}/actl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "actl"
  desc "TUI-first interactive step-debugger for GitHub Actions workflows, running locally on act"
  homepage "https://github.com/ruzmuh/actl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "actl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/actl"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    actl requires Docker to be installed and running — it launches a real job container via act.
  EOS
end
